### ISSUE TITLE
could not load needed library 'libjpgt.so' for 'liblept.so'

### ISSUE THREAD

**Issue by guoyong0423** [rmtheis/tess-two#158] opened 2016-06-27 08:00 UTC
I use 5.4.1 is correct, but update to 6.0.2, has a error : 
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1892]:  1758 could not load needed library 'libjpgt.so' for 'liblept.so' (load_library[1094]: Library 'libjpgt.so' not found)
	at java.lang.Runtime.loadLibrary(Runtime.java:370)
	at java.lang.System.loadLibrary(System.java:535)
	at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:44)
	... 16 more
Maybe TessBaseAPI.java cancel System.loadLibrary("pngt") in 6.0.2?

**Comment by rmtheis** [comment] 2016-06-27 14:04
Duplicate of #150. Please make a comment there to indicate what version of Android this is happening on.

**Closed by rmtheis** 2016-06-27 14:04 UTC
