### ISSUE TITLE
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 11237 (Thread-5)

### ISSUE THREAD

**Issue by trevorwang** [rmtheis/tess-two#213] opened 2017-06-04 06:44 UTC
Summary:
 Code is here https://github.com/trevorwang/hello-ocr
```
06-04 14:40:38.811 11164-11237/mingsin.helloocr A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 11237 (Thread-5)
                                                        
                                                        [ 06-04 14:40:38.811   407:  407 W/         ]
                                                        debuggerd: handling request: pid=11164 uid=10201 gid=10201 tid=11237
```

Steps to reproduce the issue:

1. 
2. 
3.

Expected result:

Actual result:

Crash

Tess-two version:6.3.0

Android version: 7.0

Phone/device model: Huawei P10 Plus

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):

arm64-v8a

**Comment by rmtheis** [comment] 2017-06-13 04:14
Thanks for the report. Duplicate of #197.

**Closed by rmtheis** 2017-06-13 04:14 UTC
