### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc

### ISSUE THREAD

**Issue by wangyangke** [rmtheis/tess-two#220] opened 2017-08-03 09:08 UTC
Test under android 5.0 phone doesn't crash, but more than 5.0 of 100%
this is logcat :
08-03 16:46:11.239 9888-9888/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-03 16:46:11.239 9888-9888/? A/DEBUG: Build fingerprint: 'google/angler/angler:7.1.2/N2G47O/3852959:user/release-keys'
08-03 16:46:11.239 9888-9888/? A/DEBUG: Revision: '0'
08-03 16:46:11.239 9888-9888/? A/DEBUG: ABI: 'arm64'
08-03 16:46:11.240 9888-9888/? A/DEBUG: pid: 9559, tid: 9559, name: inxindai.borrow  >>> com.xinxindai.borrow <<<
08-03 16:46:11.240 9888-9888/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc
08-03 16:46:11.240 9888-9888/? A/DEBUG:     x0   0000007938d4ae80  x1   0000000000000001  x2   0000000000000000  x3   0000000000000000
08-03 16:46:11.240 9888-9888/? A/DEBUG:     x4   0000000000000000  x5   0000000000000000  x6   0000800000000000  x7   0000000000000000
08-03 16:46:11.240 9888-9888/? A/DEBUG:     x8   0000000000000000  x9   0000000000000000  x10  000000791980c360  x11  0000000000000010
08-03 16:46:11.240 9888-9888/? A/DEBUG:     x12  0000007938c0c678  x13  0000000000000820  x14  000000000000000c  x15  0000000000000000
08-03 16:46:11.240 9888-9888/? A/DEBUG:     x16  000000791b78e930  x17  000000791b52d030  x18  0000000000000000  x19  0000000000000000
08-03 16:46:11.240 9888-9888/? A/DEBUG:     x20  0000007919973ee0  x21  0000007919913b40  x22  0000000000000000  x23  0000000000000000
08-03 16:46:11.240 9888-9888/? A/DEBUG:     x24  0000000000000000  x25  00000079199161e0  x26  000000793cb2ab30  x27  0000007919862800
08-03 16:46:11.240 9888-9888/? A/DEBUG:     x28  0000007fc52f09f0  x29  0000007fc52f08c0  x30  000000791b49472c
08-03 16:46:11.240 9888-9888/? A/DEBUG:     sp   0000007fc52f0740  pc   000000791b494748  pstate 0000000080000000
08-03 16:46:11.247 9888-9888/? A/DEBUG: backtrace:
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #00 pc 00000000000b7748  /data/app/com.xinxindai.borrow-2/lib/arm64/libtess.so (_ZN9tesseract9Tesseract15recog_all_wordsEP8PAGE_RESP10ETEXT_DESCPK4TBOXPKci+176)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #01 pc 00000000000a55c0  /data/app/com.xinxindai.borrow-2/lib/arm64/libtess.so (_ZN9tesseract11TessBaseAPI9RecognizeEP10ETEXT_DESC+848)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #02 pc 00000000000a3cd0  /data/app/com.xinxindai.borrow-2/lib/arm64/libtess.so (_ZN9tesseract11TessBaseAPI11GetUTF8TextEv+60)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #03 pc 0000000000268b10  /data/app/com.xinxindai.borrow-2/lib/arm64/libtess.so (Java_com_googlecode_tesseract_android_TessBaseAPI_nativeGetUTF8Text+64)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #04 pc 00000000000dbd90  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #05 pc 00000000000d27b4  /system/lib64/libart.so (art_quick_invoke_stub+580)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #06 pc 00000000000df480  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+208)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #07 pc 000000000029084c  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+312)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #08 pc 0000000000289838  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+596)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #09 pc 000000000055af9c  /system/lib64/libart.so (MterpInvokeDirect+392)
08-03 16:46:11.247 9888-9888/? A/DEBUG:     #10 pc 00000000000c5294  /system/lib64/libart.so (ExecuteMterpImpl+14484)

**Comment by rmtheis** [comment] 2017-08-03 15:28
Thanks for the info. Duplicate of #197.

**Closed by rmtheis** 2017-08-03 15:28 UTC
