### ISSUE TITLE
 Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 514

### ISSUE THREAD

**Issue by wangyangke** [rmtheis/tess-two#219] opened 2017-08-03 02:03 UTC
I in the project with Tess - two, but encountered this problem Fatal signal 11 (SIGSEGV), code 1, fault addr 0 xc dar in 514

**Comment by rmtheis** [comment] 2017-08-03 03:31
Not enough info. Likely duplicate of #197.

**Closed by rmtheis** 2017-08-03 03:31 UTC

**Comment by wangyangke** [comment] 2017-08-03 04:00
Before android sdk5.0 is right, and do not throw Fatal signal 11 (SIGSEGV), but android 5.0 came later, I now the equipment is the android 6.0

**Comment by wangyangke** [comment] 2017-08-03 05:09
No one encountered this problem?

**Comment by dukezhao** [comment] 2017-08-09 11:14
I meet this problem too , how to fix it ?
when I open a local pic to enter the method  :nativeInit(datapath, language);
it crashed & log 
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 26354 (Thread-21941)

my device: huawei kiw_AL10，android 6.0.1
