### ISSUE TITLE
Crash with error: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 32614

### ISSUE THREAD

**Issue by michaelDnguyen** [rmtheis/tess-two#214] opened 2017-06-13 08:25 UTC
Summary:
I call method normally:

`
baseApi.clear();
baseApi.setImage(ReadFile.readBitmap(bmp));
String recognizedText = baseApi.getUTF8Text();
`

And the application crashed in logger as follows:

`
06-13 15:02:58.378: A/libc(32614): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 32614 (com.dlvn.dlpad)
06-13 15:02:58.488: I/DEBUG(16561): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-13 15:02:58.488: I/DEBUG(16561): Build fingerprint: 'samsung/matisse3gxx/matisse3g:5.0.2/LRX22G/T531XXS1BQA2:user/release-keys'
06-13 15:02:58.488: I/DEBUG(16561): Revision: '3'
06-13 15:02:58.488: I/DEBUG(16561): ABI: 'arm'
06-13 15:02:58.488: I/DEBUG(16561): pid: 32614, tid: 32614, name: com.dlvn.dlpad  >>> com.dlvn.dlpad <<<
06-13 15:02:58.488: I/DEBUG(16561): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
06-13 15:02:58.518: I/DEBUG(16561):     r0 00000000  r1 97a6bb80  r2 ffffffff  r3 00000040
06-13 15:02:58.518: I/DEBUG(16561):     r4 b6f4de04  r5 00000000  r6 bed31768  r7 97a6bb80
06-13 15:02:58.518: I/DEBUG(16561):     r8 96019000  r9 94fad100  sl 94f975b8  fp 96019000
06-13 15:02:58.518: I/DEBUG(16561):     ip ffffffc8  sp bed31760  lr b6f2b9ad  pc 9de02aa6  cpsr 600b0030
06-13 15:02:58.518: I/DEBUG(16561): backtrace:
06-13 15:02:58.518: I/DEBUG(16561):     #00 pc 000c6aa6  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Classify::CharNormClassifier(TBLOB*, tesseract::TrainingSample const&, ADAPT_RESULTS*)+117)
06-13 15:02:58.518: I/DEBUG(16561):     #01 pc 000c7be9  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Classify::DoAdaptiveMatch(TBLOB*, ADAPT_RESULTS*)+160)
06-13 15:02:58.518: I/DEBUG(16561):     #02 pc 000c7ccb  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Classify::AdaptiveClassifier(TBLOB*, BLOB_CHOICE_LIST*)+94)
06-13 15:02:58.518: I/DEBUG(16561):     #03 pc 0013ce05  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Wordrec::call_matcher(TBLOB*)+38)
06-13 15:02:58.518: I/DEBUG(16561):     #04 pc 0013ce3b  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Wordrec::classify_blob(TBLOB*, char const*, C_COL, BlamerBundle*)+22)
06-13 15:02:58.518: I/DEBUG(16561):     #05 pc 0013b531  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Wordrec::classify_piece(GenericVector<SEAM*> const&, short, short, char const*, TWERD*, BlamerBundle*)+68)
06-13 15:02:58.518: I/DEBUG(16561):     #06 pc 0013569b  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Wordrec::chop_word_main(WERD_RES*)+234)
06-13 15:02:58.518: I/DEBUG(16561):     #07 pc 0013cd7b  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Wordrec::cc_recog(WERD_RES*)+26)
06-13 15:02:58.518: I/DEBUG(16561):     #08 pc 000a1aad  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Tesseract::recog_word_recursive(WERD_RES*)+36)
06-13 15:02:58.518: I/DEBUG(16561):     #09 pc 000a1be1  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Tesseract::recog_word(WERD_RES*)+96)
06-13 15:02:58.518: I/DEBUG(16561):     #10 pc 0009b7f3  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Tesseract::tess_segment_pass_n(int, WERD_RES*)+58)
06-13 15:02:58.518: I/DEBUG(16561):     #11 pc 000810ef  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Tesseract::match_word_pass_n(int, WERD_RES*, ROW*, BLOCK*)+34)
06-13 15:02:58.518: I/DEBUG(16561):     #12 pc 0008120d  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Tesseract::classify_word_pass1(tesseract::WordData const&, WERD_RES**, tesseract::PointerVector<WERD_RES>*)+64)
06-13 15:02:58.518: I/DEBUG(16561):     #13 pc 00081f79  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Tesseract::RetryWithLanguage(tesseract::WordData const&, void (tesseract::Tesseract::*)(tesseract::WordData const&, WERD_RES**, tesseract::PointerVector<WERD_RES>*), WERD_RES**, tesseract::PointerVector<WERD_RES>*)+104)
06-13 15:02:58.518: I/DEBUG(16561):     #14 pc 000823b5  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Tesseract::classify_word_and_language(int, PAGE_RES_IT*, tesseract::WordData*)+228)
06-13 15:02:58.518: I/DEBUG(16561):     #15 pc 000836cf  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Tesseract::RecogAllWordsPassN(int, ETEXT_DESC*, PAGE_RES_IT*, GenericVector<tesseract::WordData>*)+378)
06-13 15:02:58.518: I/DEBUG(16561):     #16 pc 00083d2b  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::Tesseract::recog_all_words(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*, int)+322)
06-13 15:02:58.518: I/DEBUG(16561):     #17 pc 00079367  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::TessBaseAPI::Recognize(ETEXT_DESC*)+454)
06-13 15:02:58.518: I/DEBUG(16561):     #18 pc 00079a73  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (tesseract::TessBaseAPI::GetUTF8Text(ETEXT_DESC*)+30)
06-13 15:02:58.518: I/DEBUG(16561):     #19 pc 0013dfa5  /data/app/com.dlvn.dlpad-2/lib/arm/libtess.so (Java_com_googlecode_tesseract_android_TessBaseAPI_nativeGetUTF8Text+84)
06-13 15:02:58.518: I/DEBUG(16561):     #20 pc 002a5c63  /data/dalvik-cache/arm/data@app@com.dlvn.dlpad-2@base.apk@classes.dex
06-13 15:02:58.548: I/Timeline(918): Timeline: Activity_windows_visible id: ActivityRecord{1f9b13c0 u0 com.dlvn.dlpad/.esubmission.SubmissionActivity2 t1309} time:372375803
`

I can not find the cause of this problem, tess-two version that I use quite old (last edit in 2015) and for some reason I did not apply the new version.
A few days ago I still call the method operation normal, I just made the edit on the image. please help me for this problem.

Steps to reproduce the issue:
1. 
2. 
3.

Expected result:
Crash

Actual result:
Recognizes text on images without incident

Tess-two version: old, release mid 2015

Android version: Android 5.1.1

Phone/device model: Samsung galaxy A7 2016

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):

**Comment by rmtheis** [comment] 2017-06-13 13:59
Thanks for the report. Duplicate of #197.

**Closed by rmtheis** 2017-06-13 13:59 UTC
