### ISSUE TITLE
Build failure with Android Studio 3 and Gradle 4.3.1

### ISSUE THREAD

**Issue by halkar** [rmtheis/tess-two#229] opened 2017-11-11 04:18 UTC
Summary:
Command `./gradlew assemble` fails with:

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/artur/sources/tess-two/eyes-two/build.gradle' line: 3
> 
> * What went wrong:
> A problem occurred evaluating project ':eyes-two'.
> > Failed to apply plugin [id 'com.android.library']
>    > Your project contains 2 or more modules with the same identification com.rmtheis:tess-two
>      at ":" and ":tess-two".
>      You must use different identification (either name or group) for each modules.

Steps to reproduce the issue:

1. Clone repository
2. run gradlew assemble --debug
3. observe quoted errors

Expected result:
build is successful

Actual result:
build fails

Tess-two version:
master branch (8.0.0)

Android version:
n/a

Phone/device model:
n/a

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):
n/a

Link to training data used:
n/a

Link to image used as input:
n/a

**Comment by rmtheis** [comment] 2017-11-11 16:59
Thanks for the report. Duplicate of #167. One of the workarounds listed on that issue should work for you.

**Closed by rmtheis** 2017-11-11 16:59 UTC
